### ISSUE TITLE
[Question]: cannot write to files and stdout at the same time

### ISSUE THREAD

**Issue by pplmx** [uber-go/zap#1026]
# Here is my example.
`go run logger.go` will throw the following error:
```text
$ go run logger.go
panic: sync /dev/stdout: The handle is invalid.

goroutine 1 [running]:
main.createLogger.func4(0x96f830)
        C:/Users/purpl/JetBrains/GolandProjects/LearningGo/log/logger.go:111 +0x3c
main.createLogger()
        C:/Users/purpl/JetBrains/GolandProjects/LearningGo/log/logger.go:114 +0x887
main.main()
        C:/Users/purpl/JetBrains/GolandProjects/LearningGo/log/logger.go:17 +0x19
exit status 2
```

## logger.go

```go
package main

import (
    "fmt"
    "go.uber.org/zap"
    "go.uber.org/zap/zapcore"
    "os"
)

const (
    BaseLog = "/var/log"
    AppLog  = BaseLog + "/app"
)

var LOG *zap.Logger

func main() {
    LOG = createLogger()
    LOG.Error("hi")
}

func createLogger() *zap.Logger {
    // First, define our level-handling logic.
    highPriority := zap.LevelEnablerFunc(func(lvl zapcore.Level) bool {
        return lvl >= zapcore.ErrorLevel
    })
    stdPriority := zap.LevelEnablerFunc(func(lvl zapcore.Level) bool {
        return lvl >= zapcore.InfoLevel
    })
    lowPriority := zap.LevelEnablerFunc(func(lvl zapcore.Level) bool {
        return lvl >= zapcore.DebugLevel
    })

    // write to the files or the stdout[stderr]
    fileDebug := getWriteSyncer("./debug.log")
    fileStd := getWriteSyncer("./app.log")
    fileError := getWriteSyncer("./error.log")
    consoleDebug := zapcore.Lock(os.Stdout)

    enc := zap.NewProductionEncoderConfig()
    enc.TimeKey = "time"
    enc.EncodeTime = zapcore.TimeEncoderOfLayout("2006-01-02 15:04:05.000Z0700")
    fileEncoder := zapcore.NewJSONEncoder(enc)
    consoleEncoder := zapcore.NewConsoleEncoder(zap.NewDevelopmentEncoderConfig())

    // Join the outputs, encoders, and level-handling functions into
    // zapcore.Cores, then tee the four cores together.
    core := zapcore.NewTee(
        zapcore.NewCore(fileEncoder, fileError, highPriority),
        zapcore.NewCore(fileEncoder, fileStd, stdPriority),
        zapcore.NewCore(fileEncoder, fileDebug, lowPriority),
        zapcore.NewCore(consoleEncoder, consoleDebug, lowPriority),
    )

    // From a zapcore.Core, it's easy to construct a Logger.
    logger := zap.New(core, zap.Fields(zap.String("app", "octopus")))
    defer func(logger *zap.Logger) {
        err := logger.Sync()
        if err != nil {
            panic(err)
        }
    }(logger)
    return logger
}

func getWriteSyncer(path string) zapcore.WriteSyncer {
    file, err := os.OpenFile(path, os.O_RDWR|os.O_APPEND|os.O_CREATE, 644)
    if err != nil {
        panic(err)
    }
    return zapcore.AddSync(file)
}

```

## Env
```shell
$ go version
go version go1.17.3 windows/amd64

OS Name:	Microsoft Windows 10 Pro
Version:	10.0.19043 Build 19043
```

**Comment by abhinav** [comment]
Hello! The think that the error is from the same reason as #991: Sync is not allowed on os.Stdout if it's being fed to a terminal.

For example, given this minimal program:

```go
package main

import (
	"fmt"
	"os"
)

func main() {
	fmt.Println(os.Stdout.Sync())
}
```

It prints an error if I run it directly in my terminal.

```
$ go run tmp.go
sync /dev/stdout: inappropriate ioctl for device
```

But if I pipe it to a file, it will report no error:

```
$ go run tmp.go > log.txt
$ cat log.txt
<nil>
```

As in that diff, I suggest ignoring that error on Sync.

---

Separately, I should mention that `getWriteSyncer` should not call `zapcore.AddSync`. `*os.File` is a zapcore.WriteSyncer already so you can return it as-is.

```go
func getWriteSyncer(path string) zapcore.WriteSyncer {
    file, err := os.OpenFile(path, os.O_RDWR|os.O_APPEND|os.O_CREATE, 644)
    if err != nil {
        panic(err)
    }
    return file
}
```

Hope this helps!

**Comment by pplmx** [comment]
Thanks a lot. @abhinav 
It works fine.

> I believe the issue is that `File.Sync()` on a stdout that is not fed into a TTY is "not allowed". On a macOS machine, the error from the example above is:
> 
> ```
> sync /dev/stdout: inappropriate ioctl for device
> ```
> 
> This refers to the unix error ENOTTY. I'm not sure what the Windows equivalent of that is. At least on Unix systems, you can probably guard against this with:
> 
> ```
> // import "syscall"
> 
> err := logger.Sync()
> if err != nil && !errors.Is(err, syscall.ENOTTY) {
>   fmt.Println(err)
> }
> ```
