### ISSUE TITLE
Panicw does not log any of the word arguments

### ISSUE THREAD

**Issue by samsondav** [uber-go/zap#1170]
**Describe the bug**
Using [panicw](https://pkg.go.dev/go.uber.org/zap#SugaredLogger.Panicw) only logs the main message, it does not log any of the words passed.

**To Reproduce**
Log something like this:

`lggr.Panicw("foo", "bar", "baz")`

**Expected behavior**
I would expect "bar" and "baz" to appear in the panic/log output. Instead I see just this:

```
panic: foo

goroutine 520 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x80?, 0x1?, {0x2?, 0x0?, 0x0?})
	/Users/sam/.asdf/installs/golang/1.18.4/packages/pkg/mod/go.uber.org/zap@v1.23.0/zapcore/entry.go:198 +0x80
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0x1400094e4e0, {0x140036cc180, 0x1, 0x2})
	/Users/sam/.asdf/installs/golang/1.18.4/packages/pkg/mod/go.uber.org/zap@v1.23.0/zapcore/entry.go:264 +0x2b8
go.uber.org/zap.(*SugaredLogger).log(0x14001f78980, 0x4, {0x1063ce3f7?, 0x0?}, {0x0?, 0x105e127f4?, 0x20?}, {0x140026b6c40, 0x2, 0x2})
	/Users/sam/.asdf/installs/golang/1.18.4/packages/pkg/mod/go.uber.org/zap@v1.23.0/sugar.go:287 +0xec
go.uber.org/zap.(*SugaredLogger).Panicw(0x1?, {0x1063ce3f7?, 0x140031b8518?}, {0x140026b6c40?, 0x14000302d80?, 0xff?})
	/Users/sam/.asdf/installs/golang/1.18.4/packages/pkg/mod/go.uber.org/zap@v1.23.0/sugar.go:227 +0x4c
```

I created a playground to try to reproduce:

https://go.dev/play/p/0w0k3OPASL9

It logs here sometimes, perhaps this is due to some kind of sync/race issue?

**Comment by samsondav** [comment]
User error.
