### ISSUE TITLE
concurrent map read/write

### ISSUE THREAD

**Issue by ammario** [uber-go/zap#616]
Stack:

```
fatal error: concurrent map read and map write

goroutine 119 [running]:
runtime.throw(0xb33a9d, 0x21)
	/usr/local/go/src/runtime/panic.go:616 +0x81 fp=0xc4201e6808 sp=0xc4201e67e8 pc=0x42c9c1
runtime.mapaccess2(0xa34b20, 0xc4202a48a0, 0xc42039aab0, 0xc4202d0601, 0xa)
	/usr/local/go/src/runtime/hashmap.go:409 +0x225 fp=0xc4201e6850 sp=0xc4201e6808 pc=0x4093a5
reflect.mapaccess(0xa34b20, 0xc4202a48a0, 0xc42039aab0, 0xc4202a48a0)
	/usr/local/go/src/runtime/hashmap.go:1195 +0x3f fp=0xc4201e6888 sp=0xc4201e6850 pc=0x40b65f
reflect.Value.MapIndex(0xa34b20, 0xc4201c83c8, 0x95, 0x9ebc40, 0xc42039aab0, 0x98, 0x9ebc40, 0xc42039aaf0, 0x98)
	/usr/local/go/src/reflect/value.go:1081 +0x126 fp=0xc4201e6910 sp=0xc4201e6888 pc=0x4b62b6
encoding/json.(*mapEncoder).encode(0xc4200b0188, 0xc4200cad10, 0xa34b20, 0xc4201c83c8, 0x95, 0x100)
	/usr/local/go/src/encoding/json/encode.go:684 +0x40d fp=0xc4201e6a70 sp=0xc4201e6910 pc=0x55eb6d
encoding/json.(*mapEncoder).(encoding/json.encode)-fm(0xc4200cad10, 0xa34b20, 0xc4201c83c8, 0x95, 0x100)
	/usr/local/go/src/encoding/json/encode.go:700 +0x64 fp=0xc4201e6ab0 sp=0xc4201e6a70 pc=0x568ff4
encoding/json.(*structEncoder).encode(0xc42051ea50, 0xc4200cad10, 0xac1940, 0xc4201c8380, 0x99, 0x100)
	/usr/local/go/src/encoding/json/encode.go:639 +0x255 fp=0xc4201e6c10 sp=0xc4201e6ab0 pc=0x55e3d5
encoding/json.(*structEncoder).(encoding/json.encode)-fm(0xc4200cad10, 0xac1940, 0xc4201c8380, 0x99, 0x100)
	/usr/local/go/src/encoding/json/encode.go:653 +0x64 fp=0xc4201e6c50 sp=0xc4201e6c10 pc=0x568f74
encoding/json.(*structEncoder).encode(0xc42037eb10, 0xc4200cad10, 0xa883a0, 0xc4201c8380, 0x99, 0xa80100)
	/usr/local/go/src/encoding/json/encode.go:639 +0x255 fp=0xc4201e6db0 sp=0xc4201e6c50 pc=0x55e3d5
encoding/json.(*structEncoder).(encoding/json.encode)-fm(0xc4200cad10, 0xa883a0, 0xc4201c8380, 0x99, 0xc4201c0100)
	/usr/local/go/src/encoding/json/encode.go:653 +0x64 fp=0xc4201e6df0 sp=0xc4201e6db0 pc=0x568f74
encoding/json.(*encodeState).reflectValue(0xc4200cad10, 0xa883a0, 0xc4201c8380, 0x99, 0x100)
	/usr/local/go/src/encoding/json/encode.go:325 +0x82 fp=0xc4201e6e28 sp=0xc4201e6df0 pc=0x55c232
encoding/json.(*encodeState).marshal(0xc4200cad10, 0xa883a0, 0xc4201c8380, 0x100, 0x0, 0x0)
	/usr/local/go/src/encoding/json/encode.go:298 +0xa5 fp=0xc4201e6e60 sp=0xc4201e6e28 pc=0x55bf25
encoding/json.Marshal(0xa883a0, 0xc4201c8380, 0xc4201e6f10, 0x4714fa, 0xc420456128, 0x3, 0x6)
	/usr/local/go/src/encoding/json/encode.go:161 +0x5f fp=0xc4201e6ea8 sp=0xc4201e6e60 pc=0x55baff
go.coder.com/hypercon/vendor/go.uber.org/zap/zapcore.(*jsonEncoder).AddReflected(0xc4203a8320, 0xb224c7, 0x7, 0xa883a0, 0xc4201c8380, 0xc4204561a8, 0xc4201e6f80)
	/home/ammar/go/src/go.coder.com/hypercon/vendor/go.uber.org/zap/zapcore/json_encoder.go:128 +0x3f fp=0xc4201e6f28 sp=0xc4201e6ea8 pc=0x71453f
go.coder.com/hypercon/vendor/go.uber.org/zap/zapcore.consoleEncoder.AddReflected(0xc4203a8320, 0xb224c7, 0x7, 0xa883a0, 0xc4201c8380, 0xc4204a4da0, 0xc4201e7040)
	<autogenerated>:1 +0x5c fp=0xc4201e6f70 sp=0xc4201e6f28 pc=0x71eb2c
go.coder.com/hypercon/vendor/go.uber.org/zap/zapcore.Field.AddTo(0xb224c7, 0x7, 0x16, 0x0, 0x0, 0x0, 0xa883a0, 0xc4201c8380, 0x7fbca445f220, 0xc4203a8320)
	/home/ammar/go/src/go.coder.com/hypercon/vendor/go.uber.org/zap/zapcore/field.go:159 +0xaa4 fp=0xc4201e7050 sp=0xc4201e6f70 pc=0x713724
go.coder.com/hypercon/vendor/go.uber.org/zap/zapcore.addFields(0x7fbca445f220, 0xc4203a8320, 0xc42038a700, 0x1, 0x1)
	/home/ammar/go/src/go.coder.com/hypercon/vendor/go.uber.org/zap/zapcore/field.go:199 +0x62 fp=0xc4201e70b8 sp=0xc4201e7050 pc=0x713d62
go.coder.com/hypercon/vendor/go.uber.org/zap/zapcore.(*ioCore).With(0xc42037f500, 0xc42038a700, 0x1, 0x1, 0x9f3700, 0xc4201c8301)
	/home/ammar/go/src/go.coder.com/hypercon/vendor/go.uber.org/zap/zapcore/core.go:74 +0x91 fp=0xc4201e70f8 sp=0xc4201e70b8 pc=0x710261
go.coder.com/hypercon/vendor/go.uber.org/zap.(*Logger).With(0xc4201c2a80, 0xc42038a700, 0x1, 0x1, 0xb224c7)
< our stuff >
```

Can't reproduce on demand

Edit: happened twice so far.

**Comment by ammario** [comment]
After further investigation, it seems likely this was caused by a race condition in my code with an object passed into Zap.
