### ISSUE TITLE
Trivial Crash Example: Loading JSON logger config

### ISSUE THREAD

**Issue by rodgarrison** [uber-go/zap#656]
the doc on the JSON configs could use some cleanup and clarification, anyway:

```
{
  "level": "debug",
  "encoding": "json",
  "outputPaths": ["./log"],
  "encoderConfig": {
    "messageKey": "message",
    "levelKey": "level",
    "levelEncoder": "lowercase",
    "timeKey": "ts",
    "callerKey": "caller"
  }
}
```

with code:

```
package main

import "os"
import "io/ioutil"
import "encoding/json"
import "go.uber.org/zap"

var Logger *zap.Logger

func init() {
    fid, err := os.Open("./logger.json")                                                                                                      
    if (err != nil) {                                                                                                               
        os.Stderr.WriteString(err.Error()+"\n")                                                                                     
        os.Exit(3)
    }  
    stream, err := ioutil.ReadAll(fid)
    if (err != nil) {
        os.Stderr.WriteString(err.Error()+"\n")
        os.Exit(3)
    }
    var loggerCfg zap.Config
    if err := json.Unmarshal(stream, &loggerCfg); err != nil {
        os.Stderr.WriteString(err.Error()+"\n")
        os.Exit(3)
    }
    Logger, err := loggerCfg.Build()
    if err != nil {
        os.Stderr.WriteString(err.Error()+"\n")
        os.Exit(3)
    }
    defer Logger.Sync()

    Logger.Error("error logger initialized")
    Logger.Warn("warn logger initialized")
    Logger.Info("info logger initialized")
    Logger.Debug("debug logger initialized")
}

func main() {
    return
}
```

produces:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10e0848]

goroutine 1 [running]:
go.uber.org/zap/zapcore.(*jsonEncoder).AppendTime(0xc000092f60, 0xbef82a969c6a9110, 0x1ac4a4, 0x14d8c80)
         src/go.uber.org/zap/zapcore/json_encoder.go:256 +0x68
go.uber.org/zap/zapcore.(*jsonEncoder).AddTime(0xc000092f60, 0xc0000987fc, 0x2, 0xbef82a969c6a9110, 0x1ac4a4, 0x14d8c80)
	src/go.uber.org/zap/zapcore/json_encoder.go:170 +0x6b
go.uber.org/zap/zapcore.(*jsonEncoder).EncodeEntry(0xc000092f00, 0x2, 0xbef82a969c6a9110, 0x1ac4a4, 0x14d8c80, 0x0, 0x0, 0x12c9a2b, 0x18, 0x1, ...)
	src/go.uber.org/zap/zapcore/json_encoder.go:323 +0x909
go.uber.org/zap/zapcore.(*ioCore).Write(0xc000092f30, 0x2, 0xbef82a969c6a9110, 0x1ac4a4, 0x14d8c80, 0x0, 0x0, 0x12c9a2b, 0x18, 0x1, ...)
	src/go.uber.org/zap/zapcore/core.go:86 +0xa9
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0000d02c0, 0x0, 0x0, 0x0)
	src/go.uber.org/zap/zapcore/entry.go:215 +0xe9
go.uber.org/zap.(*Logger).Error(0xc000082420, 0x12c9a2b, 0x18, 0x0, 0x0, 0x0)
	src/go.uber.org/zap/logger.go:203 +0x7f
main.init.0()
	src/main/main.go:33 +0x1ea

**Comment by rodgarrison** [comment]
if I remove,

```
    "timeKey": "ts",
    "callerKey": "caller"
```
the code works fine.

**Comment by akshayjshah** [comment]
If your configuration indicates that you'd like to log the caller and timestamps, the config *must* indicate how you'd like those values to be formatted. Happy to take PRs to clarify documentation :)

**Comment by rodgarrison** [comment]
what about the caller key? which file(s) can I look in for the correct/possible values for it and time? once provided I may contribute a PR for your example taking a config file/JSON string.

**Comment by akshayjshah** [comment]
They're just JSON keys. Literally any string is fine.

**Comment by rodgarrison** [comment]
You're useless. If you worked for me and I found customers were getting
no-answer-answers you'd here about from me. Your second reply and you've
accomplished nothing. I'll just replace this api with something else.

**Comment by abhinav** [comment]
This is no longer productive.
