### ISSUE TITLE
unable to get err from golang 

### ISSUE THREAD

**Issue by 1a1a11a** [uber-go/zap#692]
Here is how I setup the logging 
```
func InitLogger(name string) (logger *zap.Logger, sugarlogger *zap.SugaredLogger){
	var cfg = zap.NewDevelopmentConfig()
	cfg.OutputPaths = []string{"stdout", "/tmp/log" + name}
	cfg.ErrorOutputPaths = []string{"stderr", "/tmp/logerr"+name}

	logger, err := cfg.Build()
	if err != nil {
		panic(err)
	}
	sugarlogger = logger.Sugar()
	defer logger.Sync() // flushes buffer, if any
	return logger, sugarlogger
}
```

when the program runs into error from golang (not my program), see the example below, it won't be recorded, any thoughts why? 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x699d5d]

goroutine 6 [running]:
stacktrace 
```

**Comment by prashantv** [comment]
Without the stacktrace, it's hard to see which line caused the nil dereference.

**Comment by 1a1a11a** [comment]
it is from io.*, which comes from my code.

**Comment by prashantv** [comment]
Is there any references to zap in the stacktrace at all? Can you truncate out your code, and just have the "top" of the stacktrace from zap onwards?

**Comment by 1a1a11a** [comment]
I don't have the old stack trace, here is a new one. 

```
panic: runtime error: integer divide by zero

goroutine 102978 [running]:
fe.pushToATS(0x0, 0xc0b014a000, 0x10d9215, 0x11cfe00, 0x752318, 0x4, 0xc05fdcac60, 0x0, 0x0)
    /home/ubuntu/projectX/src/fe/fe.go:128 +0xf8a
fe.pushToATS(0x0, 0xc0b014a000, 0x10d9215, 0x11cfe00, 0x752318, 0x4, 0xc05fdcac60, 0x0, 0x1)
    /home/ubuntu/projectX/src/fe/fe.go:142 +0x98c
fe.pushToATS(0x0, 0xc0b014a000, 0x10d9215, 0x11cfe00, 0x752318, 0x4, 0xc05fdcac60, 0x0, 0x2)
    /home/ubuntu/projectX/src/fe/fe.go:142 +0x98c
fe.pushToATS(0x0, 0xc0b014a000, 0x10d9215, 0x11cfe00, 0x752318, 0x4, 0xc05fdcac60, 0x0, 0x3)
    /home/ubuntu/projectX/src/fe/fe.go:142 +0x98c
fe.pushToATS(0x0, 0xc0b014a000, 0x10d9215, 0x11cfe00, 0x752318, 0x4, 0xc05fdcac60, 0x0, 0x4)
    /home/ubuntu/projectX/src/fe/fe.go:142 +0x98c
fe.pushToATS(0x0, 0xc0b014a000, 0x10d9215, 0x11cfe00, 0x752318, 0x4, 0xc05fdcac60, 0x0, 0x5)
    /home/ubuntu/projectX/src/fe/fe.go:142 +0x98c
fe.arch1.func1(0xc05fdcac60, 0x7adee0, 0xc0825ca520, 0xc04308c470, 0xc051e9c480, 0xc06b390990, 0x62a700, 0xc06774cd20, 0x98c300)
    /home/ubuntu/projectX/src/fe/arch.go:129 +0x4c3
created by fe.arch1
    /home/ubuntu/projectX/src/fe/arch.go:92 +0x83d
```

**Comment by prashantv** [comment]
Sorry I think I misunderstood your question -- I thought you were asking about why zap was crashing, but it seems like you want panics that are from your system to be captured by zap automatically.

It's not possible to attach a global handler for panics. The closest is using `defer` + `recover`, but these can only handle panics on the goroutine that ran `defer`. [Example golang-nuts thread](https://groups.google.com/d/msg/golang-nuts/-ZE33955Ktk/5910rDzEAQAJ).

The closest is you can `defer` a function that recovers, and logs using `logger.Panic`. This could be made simpler with some sort of helper function:
```go

func PanicHandler(logger *zap.Logger) {
  if r := recover(); r != nil {
    logger.Panic("caught panic", zap.Any("panicDetails", r))
    // Don't swallow the panic
    panic(r)
  }
}

func myFunc(logger *zap.Logger) {
  defer PanicHandler(logger)
  // my logic
}

```

**Comment by 1a1a11a** [comment]
Thank you!
