### ISSUE TITLE
Appending duration field when writing log causes panic

### ISSUE THREAD

**Issue by jenyad20** [uber-go/zap#784]
Happens only on specific configuration, on zap version 1.13.0
```
DefaultEncoder := zapcore.EncoderConfig{
		MessageKey:  "message",
		LevelKey:    "level",
		TimeKey:     "timestamp",
		EncodeLevel: zapcore.CapitalLevelEncoder,
		EncodeTime:  zapcore.ISO8601TimeEncoder,
	}

	var lvl zap.AtomicLevel
	err := lvl.UnmarshalText([]byte("info"))
	if err != nil {
		panic(err.Error())
	}

	cfg := zap.Config{
		Encoding: "json",
		Level:    lvl,
		OutputPaths:   []string{"stdout"},
		EncoderConfig: DefaultEncoder,
		DisableCaller: true,
	}
	l, err := cfg.Build()
	//l, err := zap.NewProduction() -- if i create the logger with this configuration the bug doesn't happen
	if err != nil {
		panic("log panic")
	}
	l.Info("test", zap.Any("duration", time.Minute))
```

this function throws a panic
```
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2928 +0x384
2020/02/09 18:38:34 http: panic serving 127.0.0.1:48362: runtime error: invalid memory address or nil pointer dereference
goroutine 73 [running]:
net/http.(*conn).serve.func1(0xc0001f0000)
        /usr/local/go/src/net/http/server.go:1767 +0x139
panic(0xa9c460, 0x10d2290)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
go.uber.org/zap/zapcore.(*jsonEncoder).AppendDuration(0xc0001eda40, 0x6b1a7)
        /home/yevgeny/IdeaProjects/go/pkg/mod/go.uber.org/zap@v1.10.0/zapcore/json_encoder.go:225 +0x53
go.uber.org/zap/zapcore.(*jsonEncoder).AddDuration(0xc0001eda40, 0xb78ac8, 0x14, 0x6b1a7)
        /home/yevgeny/IdeaProjects/go/pkg/mod/go.uber.org/zap@v1.10.0/zapcore/json_encoder.go:123 +0x57
go.uber.org/zap/zapcore.Field.AddTo(0xb78ac8, 0x14, 0x8, 0x6b1a7, 0x0, 0x0, 0x0, 0x0, 0xc715a0, 0xc0001eda40)
        /home/yevgeny/IdeaProjects/go/pkg/mod/go.uber.org/zap@v1.10.0/zapcore/field.go:126 +0x4c6
go.uber.org/zap/zapcore.addFields(0xc715a0, 0xc0001eda40, 0xc000240000, 0x9, 0x10)
        /home/yevgeny/IdeaProjects/go/pkg/mod/go.uber.org/zap@v1.10.0/zapcore/field.go:199 +0xcf
go.uber.org/zap/zapcore.(*jsonEncoder).EncodeEntry(0xc000130600, 0x2, 0xbf882b42b77f78b4, 0xdd9fbcad7, 0x115a980, 0x0, 0x0, 0xb831d2, 0x22, 0x0, ...)
        /home/yevgeny/IdeaProjects/go/pkg/mod/go.uber.org/zap@v1.10.0/zapcore/json_encoder.go:364 +0x1e4
go.uber.org/zap/zapcore.(*ioCore).Write(0xc000130630, 0x2, 0xbf882b42b77f78b4, 0xdd9fbcad7, 0x115a980, 0x0, 0x0, 0xb831d2, 0x22, 0x0, ...)
        /home/yevgeny/IdeaProjects/go/pkg/mod/go.uber.org/zap@v1.10.0/zapcore/core.go:86 +0xa9
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00022a0b0, 0xc000240000, 0x9, 0x10)
        /home/yevgeny/IdeaProjects/go/pkg/mod/go.uber.org/zap@v1.10.0/zapcore/entry.go:215 +0x117
go.uber.org/zap.(*Logger).Error(0xc000436660, 0xb831d2, 0x22, 0xc000240000, 0x9, 0x10)

```

**Comment by prashantv** [comment]
The panic is because no `EncodeDuration` was specified, so when you try to append a duration, it tries to use call the missing `EncodeDuration` function and panics.

I think this is the same as #777 -- we need more config validation so these issues are caught earlier.
