### ISSUE TITLE
Unsafe CheckedEntry re-use and data race when combining NewStdLogAt with Logger.Check

### ISSUE THREAD

**Issue by vrischmann** [uber-go/zap#842]
Hello,

there seems to a bug when combining a std logger built with [NewStdLogAt](https://pkg.go.dev/go.uber.org/zap?tab=doc#NewStdLogAt) and using [Logger.Check](https://pkg.go.dev/go.uber.org/zap?tab=doc#Logger.Check).

the following code exhibits the problems:

```go
package main

import (
	"log"
	"sync"

	"go.uber.org/zap"
)

func worker(wg *sync.WaitGroup, logger *log.Logger, workerID int) {
	defer wg.Done()

	if workerID%2 == 0 {
		for {
			logger.Println("foobar std")
		}
	} else {
		for {
			if ce := zap.L().Check(zap.DebugLevel, "foobar zap"); ce != nil {
				ce.Write(zap.Int("intfield", 200))
				ce.Write(zap.String("onefield", "string"))
			}
		}
	}
}

func main() {
	zapConfig := zap.NewDevelopmentConfig()
	zapConfig.OutputPaths = []string{"stdout"}

	zapLogger, err := zapConfig.Build()
	if err != nil {
		log.Fatal(err)
	}
	zap.ReplaceGlobals(zapLogger)

	logger, err := zap.NewStdLogAt(
		zap.L().With(zap.String("package", "foobar")),
		zap.DebugLevel,
	)
	if err != nil {
		log.Fatal(err)
	}

	var wg sync.WaitGroup
	for i := 0; i < 63; i++ {
		wg.Add(1)
		go worker(&wg, logger, i)
	}

	wg.Wait()
}
```

running this code you'll get a bunch of errors like this:
```
2020-06-22 11:56:51.198995057 +0200 CEST m=+0.029980294 Unsafe CheckedEntry re-use near Entry {Level:debug Time:2020-06-22 11:56:51.198864338 +0200 CEST m=+0.029849539 LoggerName: Message:foobar zap Caller:/home/
vincent/tmp/zap-bug/main.go:19 Stack:}.
```
triggered from [here](https://github.com/uber-go/zap/blob/master/zapcore/entry.go#L202-L209) apparently.

I also consistenly get the following panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5857c5]

goroutine 40 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0005e4370, 0xc0002ef000, 0x1, 0x1)
        /home/vincent/dev/go/pkg/mod/go.uber.org/zap@v1.15.0/zapcore/entry.go:208 +0x6b5
main.worker(0xc0000b0450, 0xc00008e140, 0x15)
        /home/vincent/tmp/zap-bug/main.go:21 +0x3b5
created by main.main
        /home/vincent/tmp/zap-bug/main.go:48 +0x426
```

and sometimes when built with `-race` I get this:
```
==================
WARNING: DATA RACE
Write at 0x00c000096420 by goroutine 7:
  go.uber.org/zap/zapcore.(*CheckedEntry).reset()
      /home/vincent/dev/go/pkg/mod/go.uber.org/zap@v1.15.0/zapcore/entry.go:182 +0x47
  go.uber.org/zap/zapcore.getCheckedEntry()
      /home/vincent/dev/go/pkg/mod/go.uber.org/zap@v1.15.0/zapcore/entry.go:46 +0x62
  go.uber.org/zap/zapcore.(*CheckedEntry).AddCore()
      /home/vincent/dev/go/pkg/mod/go.uber.org/zap@v1.15.0/zapcore/entry.go:241 +0x22e
  go.uber.org/zap/zapcore.(*ioCore).Check()
      /home/vincent/dev/go/pkg/mod/go.uber.org/zap@v1.15.0/zapcore/core.go:80 +0x83
  go.uber.org/zap.(*Logger).check()
      /home/vincent/dev/go/pkg/mod/go.uber.org/zap@v1.15.0/logger.go:275 +0x1d9
  go.uber.org/zap.(*Logger).Debug()
      /home/vincent/dev/go/pkg/mod/go.uber.org/zap@v1.15.0/logger.go:178 +0x55
  go.uber.org/zap.(*Logger).Debug-fm()
      /home/vincent/dev/go/pkg/mod/go.uber.org/zap@v1.15.0/logger.go:177 +0x73
  go.uber.org/zap.(*loggerWriter).Write()
      /home/vincent/dev/go/pkg/mod/go.uber.org/zap@v1.15.0/global.go:166 +0xe4
  log.(*Logger).Output()
      /usr/lib/golang/src/log/log.go:181 +0x39d
  log.(*Logger).Println()
      /usr/lib/golang/src/log/log.go:197 +0x77
  main.worker()
      /home/vincent/tmp/zap-bug/main.go:15 +0xe0

Previous read at 0x00c000096420 by goroutine 12:
  runtime.convT2E()
      /usr/lib/golang/src/runtime/iface.go:317 +0x0
  go.uber.org/zap/zapcore.(*CheckedEntry).Write()
      /home/vincent/dev/go/pkg/mod/go.uber.org/zap@v1.15.0/zapcore/entry.go:207 +0x5ec
  main.worker()
      /home/vincent/tmp/zap-bug/main.go:21 +0x3b4

Goroutine 7 (running) created at:
  main.main()
      /home/vincent/tmp/zap-bug/main.go:48 +0x425

Goroutine 12 (running) created at:
  main.main()
      /home/vincent/tmp/zap-bug/main.go:48 +0x425
==================
```

**Comment by prashantv** [comment]
The issue is the use of `ce.Write` multiple times here:
```go
if ce := zap.L().Check(zap.DebugLevel, "foobar zap"); ce != nil {
	ce.Write(zap.Int("intfield", 200))
	ce.Write(zap.String("onefield", "string"))
}
```

It should probably be:
```go
if ce := zap.L().Check(zap.DebugLevel, "foobar zap"); ce != nil {
	ce.Write(zap.Int("intfield", 200), zap.String("onefield", "string"))
}
```

(a single `Write` can take multiple fields)

`CheckedEntry` is not safe for re-use, it can only be used for a single `Write` call. As [documented](https://pkg.go.dev/go.uber.org/zap/zapcore?tab=doc#CheckedEntry),
> CheckedEntry references should be created by calling AddCore or Should on a nil *CheckedEntry. References are returned to a pool after Write, and MUST NOT be retained after calling their Write method.

and
> Write writes the entry to the stored Cores, returns any errors, and returns the CheckedEntry reference to a pool for immediate re-use. Finally, it executes any required CheckWriteAction.

Once the `Write` is called, the `CheckedEntry` can no longer be used.

**Comment by vrischmann** [comment]
Damn, I completely missed that thanks.
